config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :requests
  resources :availabilities
  resources :nannies
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  post   'help'   => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'admin_controll'    => 'static_pages#admin_controll'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  # Links für Header
  get 'nannies'    => 'nannies#index'
  get 'admin_optimize'  => 'static_pages#admin_optimize'
  get 'requests'    => 'requests#index'
  get 'availabilities'    => 'availabilities#index'
  get 'newnanny' => 'users#newnanny'
  get 'allclients' => 'users#indexclient'
  get 'nanniesedit'    => 'nannies#edit'
  get 'optimize'    => 'requests#optimize'
  get 'simulator'   => 'static_pages#simulator'


  # Sonstige
  get 'noaccess'    => 'static_pages#noaccess'
  get 'requestsdatatable'  => 'requests#requestsdatatable'
  get 'addtimes'    => 'availabilities#addtimes'
  get 'gamstest'    => 'options#gamstest'
  get 'read_solution'    => 'application#read_solution'
  get 'rate_nanny'    => 'nannies#rate_nanny'


  # Links für Simulator
  get 'randomrequest'   => 'simulators#randomrequest'
  get 'randompast'   => 'simulators#randompast'
  get 'tenrandompasts'   => 'simulators#tenrandompasts'
  get 'tenrandomrequests'   => 'simulators#tenrandomrequests'
  get 'randomclient'   => 'simulators#randomclient'
  get 'randomnanny'   => 'simulators#randomnanny'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # Damit unterschiedliche Startseiten erscheinen

  if logged_in?
      if admin?
        redirect_to admin_controll_path
      else
        redirect_to requests_path
      end
    end
  end

  def help

  end

  def about
  end

  def contact
  end

  def admin_controll
    if admin?
    else
      redirect_to noaccess_path
    end
  end

  def admin_optimize
    if admin?

      if Option.find(1) == nil
        Option.create(id: 1, optionname: "gamspath", value: "Hier GAMS-Pfad eintragen.. ")
      end

    else
      redirect_to noaccess_path
    end
  end

  def simulator
    if admin?
    else
      redirect_to noaccess_path
    end
  end

  def requestsdatatable
    if logged_in? == false
        redirect_to noaccess_path
    end
  end

  def noaccess
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper



end

app/views/static_pages/about.html.erb
<% provide(:title, "Informationen") %>
<h1>Informationen</h1>
<h4> Diese App wurde von Patrick Czerwinski und Sebastian Gebski entwickelt.</h4>

app/views/static_pages/admin_controll.html.erb
<% provide(:title, "Dashboard") %>
<h1>Admin Dashboard</h1>
<p>
<h3 align="center"> Auf einen Blick </h3>

<%
  Groupdate.time_zone = false

  openrequests = Request.where("status = ? OR status = ?", 0, 2).count
  nannyscount = Nanny.all.count
  clientscount = User.where(role: "client").count
  userscount = User.all.count

%>

<div>
  <div class="divcol-left">
    <h3>Aufträge & Nutzer</h3>
    <div align="center">
      <div class="dashboard-card-large">Offenen Aufträge</div>
      <div class="dashboard-card-small"><%= openrequests %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Angemeldete Nannys</div>
      <div class="dashboard-card-small"><%= nannyscount %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Angemeldete Kunden</div>
      <div class="dashboard-card-small"> <%= clientscount %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Nutzer insgesamt</div>
      <div class="dashboard-card-small"><%= userscount %></div>
    </div>


  </div>
  <div class="divcol-right">
    <h3>Aufträge in der letzten Woche</h3>


    <div align="center"> <%= column_chart Request.where(status: 1).group_by_day(:date, range: Time.now.midnight - 6.day..Time.now.midday - 1.day, format: "%a %d.%m").sum(1), width: "85%", height: "200px", label: "Aufträge: " %></div>
  </div>
</div>

<br>


<div>
  <div class="divcol-left">
    <h3>Aufträge in der nächsten Woche</h3>
    <div align="center"> <%= column_chart Request.where(status: 1).group_by_day(:date, range: Time.now..Time.now + 6.day, format: "%a %d.%m").sum(1), width: "85%", height: "200px", label: "Aufträge: " %></div>
  </div>
  <div class="divcol-right">

    <h3>Umsätze</h3>
    <div align="center">
      <div class="dashboard-card-large">Heute</div>
      <div class="dashboard-card-small"><%= Request.where(status: 1, date: Date.today).sum(5) %> €</div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Letzter Monat</div>
      <div class="dashboard-card-small"><%= Request.where(status: 1, date: (Time.now.midnight - 1.month)..Time.now).sum(5) %>
        €
      </div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Erwartet</div>
      <div class="dashboard-card-small"> <%= Request.where(status: 1, date: Time.now..(Time.now + 100.year)).sum(5) %>
        €
      </div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Gesamt</div>
      <div class="dashboard-card-small"><%= Request.where(status: 1).sum(5) %> €</div>
    </div>

  </div>
</div>

<br>



<div style="height: 650px"></div>







<div class="dashboarddiv" align="center">
  <h3 align="center"> Anzahl der Anfragen pro Tag des letzten Monats </h3>

  <%= area_chart Request.group_by_day(:date, range: Time.now.midnight - 1.month..Time.now.midday, format: "%d.%m").sum(1), width: "85%", ytitle: "Anfragen pro Tag" %>
</div>

<br>
<br>


<div class="dashboarddiv" align="center">
  <h3 align="center"> Umsatz der letzten 14 Tage </h3>

  <%= area_chart Request.where(status: 1).group_by_day(:date, range: Time.now.midnight - 14.day..Time.now.midday, format: "%a %d.%m ").sum(5), width: "85%", label: "Umsatz in €", ytitle: "Umsatz in €" %>
</div>

<br>
<br>

<div class="dashboarddiv" align="center">
  <h3 align="center"> Umsatz der letzten 12 Wochen </h3>
  <%= column_chart Request.where(status: 1).group_by_week(:date, range: Time.now.midnight - 12.week..Time.now.midday, format: "KW %V %y ").sum(5), width: "85%", label: "Umsatz in €", ytitle: "Umsatz in €" %>
</div>

<br>
<br>


<div class="dashboarddiv" align="center">
  <h3 align="center"> Aufträge pro Woche nach Nannys </h3>
  <h4 align="center"></h4>

  <%= line_chart Request.where(status: 1).group(:assigned_nanny).group_by_week(:date, range: Time.now.midnight - 12.week..Time.now.midday, format: "KW %V %y").count, width: "85%", height: "400px", label: "Aufträge: ", ytitle: "Aufträge pro Woche" %>
</div>

<br>
<br>


<div class="dashboarddiv" align="center">
  <h3 align="center"> Vergleich der Aufträge </h3>
  <h4 align="center"> Zwischen erfolgreich zugeordneten (blau bzw. 1) und nicht zugeordneten (rot, bzw. 3)
    Aufträgen. </h4>

  <%= column_chart Request.group(:status).group_by_day(:date, range: Time.now.midnight - 2.week..Time.now.midnight - 1, format: "%d.%m").count, width: "85%", height: "400px", ytitle: "Aufträge pro Tag", stacked: true %>
</div>



</p>

app/views/static_pages/admin_optimize.html.erb
<% provide(:title, "Optimierung") %>
<h1>Optimierung</h1>
<p>
<h3 align="center"> Übersicht </h3>

<%
  openrequests = Request.where("status = ? OR status = ?", 0, 2).count
  nosolutionrequests = Request.where(status: 2).count
  newrequests = Request.where(status: 0).count

  nannyscount = Nanny.all.count
  clientscount = User.where(role: "nanny").count
  userscount = User.all.count

%>



<div align="center">
  <div class="dashboard-card-large">Offenen Aufträge insgesamt</div>
  <div class="dashboard-card-small"><%= openrequests %></div>
</div>
<div align="center">
  <div class="dashboard-card-large">Neue Aufträge</div>
  <div class="dashboard-card-small"><%= newrequests %></div>
</div>
<div align="center">
  <div class="dashboard-card-large">Bisher ohne Lösung</div>
  <div class="dashboard-card-small"><%= nosolutionrequests %></div>
</div>

<br>
<br>

<h4 align="center">  <%= link_to "Optimieren", optimize_path, class: "adminbigbutton hvr-back-pulse" %>

  <%= link_to "Ergebnisse übertragen", read_solution_path, class: "adminbigbutton hvr-back-pulse" %></h4>

<br>
<br>
<h3 align="center"> GAMS-Pfad Einstellungen </h3>

<% @gams = Option.find(1)

   if @gams == nil

     @gams = Option.create(id: 1, optionname: "gamspath", value: "Hier Pfad eingeben..")

   end
%>

<%= bootstrap_form_for(@gams, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-6") do |f| %>
    <%= f.text_field :value, label: "GAMS-Pfad", label_class: "labeltext" %>
    <%= f.form_group do %>
        <h4 align="center"> <%= f.submit "Speichern", class: "homebutton hvr-back-pulse-own" %></h4>
        <h2>Bei MacOS meist im Format von:</h2>
        <h4 style="margin-top: -16px;">/Applications/GAMS24.7/sysdir/gams</h4>

        <h2>Bei Windows meist im Format von:</h2>
        <h4 style="margin-top: -16px;">C:\\GAMS\\win64\\24.5\\gams</h4>
    <% end %>

<% end %>

<h4><%= link_to "GAMS Testen", {:controller => "options", :action => "gamstest"}, class: 'homebutton hvr-back-pulse-own' %></h4>






<% $i = 0
   $num = 7

   begin
     currentnewdate = Date.today + $i

     @nannies = Nanny.all
     @nannies.each do |nan|
     nannyname = nan.name
     nannydate = Availability.find_by_sql("SELECT * FROM availabilities WHERE (nannyname = '#{nannyname}' AND date = '#{currentnewdate}')")

     if nannydate.any? == false
     @availabilities = Availability.create!(nannyname: nannyname, date: currentnewdate, morning: false, noon: false, afternoon: false, evening: false)
     end

      end
     $i +=1

   end while $i < $num

   # Prüfen welche Verfügbarkeiten in der Vergangenheit liegen und diese löschen
   @allavas = Availability.all
   @allavas.each do |ava|

     if ava.date.to_date.past?
       ava.delete
     else

     end
   end


%>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Kontakt</h1>
<h4>
  Kontakt:
  <br>
  Patrick Czerwinski: patrick.czerwinski@mail.de
  <br>
  Sebastian Gebski: gebski.sg@gmail.com
</h4>

app/views/static_pages/help.html.erb
<% provide(:title, "Anleitung") %>
<h1>Hilfe</h1>
<h4>

  Folgende Beispielaccounts können genutzt werden:
  <br>
  Nanny: nanny@test.com -> pw: foobar
  <br>
  Kunde: client@test.com -> pw: foobar
  <br>
  Admin: admin@test.com -> pw: foobar

</h4>

<h2>
  Um die Optimierung als Admin nutzen zu können, sollte zunächst der GAMS-Pfad eingetragen werden. Dies geschieht ebennfalls auf der Optimierungsseite.
</h2>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="bg"></div>
<div class="center jumbotron">
  <h1>Emergency Nanny</h1>

  <h3>
    Ihre Kinder in <b>guten</b> Händen.
  </h3>

  <%= link_to "Ich bin eine Nanny", newnanny_path, class: "homebutton hvr-fade" %>

  <%= link_to "Ich suche eine Nanny", signup_path, class: "homebutton hvr-fade" %>
</div>


<div class="bg2"></div>

<div class="center jumbotron2">

<!-- Services -->
<div >
  <h1 class="row-title">Unsere Services</h1>
  <div class="col-md-4 feature">
    <span class="glyphicon glyphicon-star"></span>
    <h3>Qualifizierte Nannys</h3>
    <p>Hohe Ansprüche? Kein Problem! Bei jeder Anfrage kannst du deine individuellen Anforderungen angeben. </p>
  </div>
  <div class="col-md-4 feature">
    <span class="glyphicon glyphicon-bullhorn"></span>
    <h3>Benutzerfreundlich</h3>
    <p>EmergencyNanny funktioniert sehr simpel. Also: Account erstellen und einfach loslegen!</p>
  </div>
  <div class="col-md-4 feature">
    <span class="glyphicon glyphicon-dashboard"></span>
    <h3>Schnelle Zuordnung</h3>
    <p>Erhalte deine optimale Nanny in kurzer Zeit. Wir ordnen neue Aufträge mehrmal täglich zu!</p>
  </div>
</div>
</div>


<!-- Team -->

<div class="bg3"></div>
<div class="center jumbotron3">
<div class="row me-row content-ct">
  <h1 class="row-title">Das Team hinter EmergencyNanny</h1>
  <div class="col-md-6 feature">
    <img src="https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-circle-512.png" style="height: 80px;width: auto;"> </img>
    <h3>B. Sc. Patrick Czerwinski</h3>
    <p style="color: #a8a8a8">Master Student in Wirtschaftswissenschaften an der Leibniz Universität Hannover. Spezialisiert auf Mobile Applikation und Design. </p>
  </div>
  <div class="col-md-6 feature">
    <img src="https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-circle-512.png" style="height: 80px;width: auto;"> </img>
    <h3>B. Sc. Sebastian Gebski</h3>
    <p style="color: #a8a8a8">Master Student in Wirtschaftswissenschaften an der Leibniz Universität Hannover. Spezialisiert auf Optimierungsmodelle und Digital Behaviour. </p>
  </div>

</div>
</div>

<!-- Registrieren -->
<div class="container-fluid tickets" id="tickets">
  <div class="row me-row content-ct">
    <a id="registernow"></a>

    <h1 class="row-title">Jetzt registrieren</h1>
    <div class="col-md-4 col-sm-6 col-md-offset-2">
      <h3 class="price">Ich bin eine Nanny</h3>
      <a href="/newnanny" class="homebutton hvr-back-pulse-own">Anmelden</a>
    </div>
    <div class="col-md-4 col-sm-6">
      <h3 class="price">Ich suche eine Nanny</h3>
      <a href="/signup" class="homebutton hvr-back-pulse-own">Anmelden</a>
    </div>
  </div>
</div>

<div style="margin-bottom: 150px;"></div>

<script>
  var jumboHeight = $('.jumbotron').outerHeight();
  function parallax(){
    var scrolled = $(window).scrollTop();
    $('.bg').css('height', (jumboHeight-scrolled) + 'px');
  }

  $(window).scroll(function(e){
    parallax();
  });

</script>

app/views/static_pages/noaccess.html.erb
<% provide(:title, 'Fehler') %>
<h1 style="margin-top: 150px;">Ups..</h1>
<h3 style="margin-bottom: 250px;">
Für diese Seite hast du keinen Zugriff :(</h3>

app/views/static_pages/simulator.html.erb
<% provide(:title, "Simulator") %>
<h1>Simulator</h1>
<p>

  <%
    openrequests = Request.where("status = ? OR status = ?", 0, 2).count
    nosolutionrequests = Request.where(status: 2).count
    newrequests = Request.where(status: 0).count

    nannyscount = Nanny.all.count
    clientscount = User.where(role: "client").count
    userscount = User.all.count

  %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-4">
    <h3>Aufträge</h3>
    <div align="center">
      <div class="dashboard-card-large">Offenen Aufträge insgesamt</div>
      <div class="dashboard-card-small"><%= openrequests %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Neue Aufträge</div>
      <div class="dashboard-card-small"><%= newrequests %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Bisher ohne Lösung</div>
      <div class="dashboard-card-small"><%= nosolutionrequests %></div>
    </div>

  </div>
  <div class="col-md-4">
    <h3>Nutzer</h3>
    <div align="center">
      <div class="dashboard-card-large">Nutzer insgesamt</div>
      <div class="dashboard-card-small"><%= userscount %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Nannys</div>
      <div class="dashboard-card-small"><%= nannyscount %></div>
    </div>
    <div align="center">
      <div class="dashboard-card-large">Kunden</div>
      <div class="dashboard-card-small"><%= clientscount %></div>
    </div>
  </div>
</div>

<br>
<br>

<h5 align="center">Einzelne Einträge generieren</h5>
<br>

<h4 align="center">
  <%= link_to "Zufällige Anfrage generieren", randomrequest_path, class: "adminsmallbutton hvr-back-pulse" %>
  <%= link_to "Vergangenen Auftrag generieren", randompast_path, class: "adminsmallbutton hvr-back-pulse" %>
</h4><h4 align="center">
  <%= link_to "Zufälligen Kunden generieren", randomclient_path, class: "adminsmallbutton hvr-back-pulse" %>
  <%= link_to "Zufällige Nanny generieren", randomnanny_path, class: "adminsmallbutton hvr-back-pulse" %>

</h4>

<br>
<h5 align="center">Mehrere Einträge generieren</h5>
<br>

<h4 align="center">  <%= link_to "10 Anfragen generieren", tenrandomrequests_path, class: "adminsmallbutton hvr-back-pulse" %>
  <%= link_to "10 vergangene Anfragen generieren", tenrandompasts_path, class: "adminsmallbutton hvr-back-pulse" %></h4>