config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :requests
  resources :availabilities
  resources :nannies
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  post   'help'   => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'admin_controll'    => 'static_pages#admin_controll'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  # Links für Header
  get 'nannies'    => 'nannies#index'
  get 'admin_optimize'  => 'static_pages#admin_optimize'
  get 'requests'    => 'requests#index'
  get 'availabilities'    => 'availabilities#index'
  get 'newnanny' => 'users#newnanny'
  get 'allclients' => 'users#indexclient'
  get 'nanniesedit'    => 'nannies#edit'
  get 'optimize'    => 'requests#optimize'
  get 'simulator'   => 'static_pages#simulator'


  # Sonstige
  get 'noaccess'    => 'static_pages#noaccess'
  get 'requestsdatatable'  => 'requests#requestsdatatable'
  get 'addtimes'    => 'availabilities#addtimes'
  get 'gamstest'    => 'options#gamstest'
  get 'read_solution'    => 'application#read_solution'
  get 'rate_nanny'    => 'nannies#rate_nanny'


  # Links für Simulator
  get 'randomrequest'   => 'simulators#randomrequest'
  get 'randompast'   => 'simulators#randompast'
  get 'tenrandompasts'   => 'simulators#tenrandompasts'
  get 'tenrandomrequests'   => 'simulators#tenrandomrequests'
  get 'randomclient'   => 'simulators#randomclient'
  get 'randomnanny'   => 'simulators#randomnanny'

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :date, presence: true
  validates :time, presence: true
  validates :willingness_to_pay, allow_nil: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 500}
  validates :maxage, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100}, allow_nil: true
  validates :minage, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100}, allow_nil: true

  belongs_to :user
  belongs_to :nanny
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :checkloggedin
  before_action :checknanny, only: [:new, :edit, :update, :create, :destroy]
  before_action :correct_user_request, only: [:show, :edit]
  before_action :checkstatus, only: [:edit, :destroy]

  def checkstatus
    if @request.status == 0 or @request.status == 2
    else
      redirect_to noaccess_path
      flash[:danger] = "Vergangene oder zugeordnete Aufträge können nicht bearbeitet werden."

    end
  end


  def correct_user_request
    if admin?
    elsif client?
      @user = User.find_by_name(@request.name)
      redirect_to(noaccess_path) unless current_user?(@user)
    elsif nanny?
      @user = User.find_by_name(@request.assigned_nanny)
      redirect_to(noaccess_path) unless current_user?(@user)
    end
  end


  def checknanny
    if nanny?
      redirect_to noaccess_path
    else
    end
  end


  def checkloggedin
    if logged_in?
    else
      flash[:danger] = "Kein Zugriff. Bitte einloggen."
      redirect_to login_path
    end
  end

  # GET /requests
  # GET /requests.json
  def index


    if admin?
      @requests0 = Request.all

    else
      if client?
        @requests0 = Request.where(name: current_user.name)

      else
        if nanny?
          # Zuerst prüfen ob die Nanny-Daten bereits hinzugefügt wurden, wenn nicht dann muss dies zunächst geschehen
          nannythere = Nanny.find_by_sql("SELECT * FROM nannies WHERE name = '#{current_user.name}'")


          if nannythere.any? == false
            flash[:warning] = "Hinweis: Bevor die Aufträge eingesehen werden können, müssen die Nanny Daten eingetragen werden."

            redirect_to new_nanny_path
            @requests0 = Request.where(assigned_nanny: current_user.name)

          else
            @requests0 = Request.where(assigned_nanny: current_user.name)

          end
        end
      end
    end

    # Den korrekten View auch auswählen

    @whichview = params[:whichview]
    if @whichview == nil
      # Definiert den "Standard-View"
      @whichview = "onlynew"
    end

    if @whichview == "onlyold"
      @requests1 = @requests0.where(date: (Time.now.midnight - 100.year)..Time.now.midnight)
    elsif @whichview == "onlynew"
      @requests1 = @requests0.where(date: Time.now.midnight..(Time.now.midnight + 99.year))
    elsif @whichview == "lastweek"
      @requests1 = @requests0.where(date: (Time.now.midnight - 1.week)..Time.now.midnight)
    else
      @requests1 = @requests0
    end

    # Ordnet die Anfragen
    @requests = @requests1.sort_by { |request| request.date }.reverse


  end


  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request }
        format.json { render :show, status: :created, location: @request }
        flash[:success] = "Anfrage erfolgreich erstellt."

      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request }
        format.json { render :show, status: :ok, location: @request }
        flash[:success] = "Anfrage erfolgreich aktualisiert."

      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
      flash[:success] = "Anfrage erfolgreich gelöscht."
    end
  end

  def requestsdatatable
    if admin?
      @requests0 = Request.all
    else
      if client?
        @requests0 = Request.where(name: current_user.name)
      else
        if nanny?
          @requests0 = Request.where(assigned_nanny: current_user.name)
        end
      end
    end

    @requests = @requests0

  end


  def optimize

    # Zunächst wird die Include Datei aufgebaut

    if File.exist?("include.inc")
      File.delete("include.inc")
    end

    # INCLUDE DATEI AUFBAUEN  -------------------------

    f=File.new("include.inc", "w")

    # SETS
    printf(f, "set i / \n")
    @nannies = Nanny.all
    @nannies.each { |nan| printf(f, nan.name + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "j / \n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |req| printf(f, req.name + "-" + req.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "t / \n")

    @i = 0
    (1..7).each { |t| printf(f, (Date.today + @i).to_s + "\n")
    @i+=1 }

    printf(f, "/" + "\n\n")

    printf(f, "s / \n")
    printf(f, "morning" + "\n")
    printf(f, "noon" + "\n")
    printf(f, "afternoon" + "\n")
    printf(f, "evening" + "\n")
    printf(f, "/;" + "\n\n")

    # PARAMETER

    #Provisionssatz (ist fix)

    printf(f, "Parameter\n  r /\n")
    printf(f, "5" + "\n")
    printf(f, "/" + "\n\n")

    # Zeiten

    printf(f, "Parameter\n  tV(i,t,s) /\n")

    # Verfügbarkeiten der Nannys

    @nannies = Nanny.all
    @nannies.each { |l|

      @availabilites = Availability.where(nannyname: l.name)
      @availabilites.each { |k|

        if k.morning == 1
          printf(f, l.name + "." + k.date + "." + "morning" + "     1" "\n")
        end

        if k.noon == 1
          printf(f, l.name + "." + k.date + "." + "noon" + "     1" + "\n")
        end

        if k.afternoon == 1
          printf(f, l.name + "." + k.date + "." + "afternoon" + "     1"+ "\n")
        end

        if k.evening == 1
          printf(f, l.name + "." + k.date + "." + "evening" + "     1" + "\n")
        end
      }
    }
    printf(f, "/" + "\n\n")


    # Gewünschte Zeiten der Anfragen

    printf(f, "Parameter\n  tG(j,t,s) /\n")

    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |l|
      printf(f, l.name + "-" + l.id.to_s + "." + l.date + "." + l.time + "     1" + "\n")
    }
    printf(f, "/" + "\n\n")


    # Führerscheine -------------

    # Führerscheine der Nannys

    printf(f, "Parameter\n  FV(i) /\n")
    @nannies = Nanny.all
    @nannies.each { |nan|
      if nan.driverlicense == true
        printf(f, nan.name + "   " + "1" + "\n")
      else
        printf(f, nan.name + "   " + "0" + "\n")
      end
    }
    printf(f, "/" + "\n\n")

    # Führerscheinnachfragen bei den Anfragen

    printf(f, "Parameter\n  FG(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |req|
      if req.driverlicense == true
        printf(f, req.name + "-" + req.id.to_s + "   " + "1" + "\n")
      else
        printf(f, req.name + "-" + req.id.to_s + "   " + "0" + "\n")
      end
    }
    printf(f, "/" + "\n\n")

    printf(f, "Parameter\n  BF(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |req|
      if req.driverlicense == false
        printf(f, req.name + "-" + req.id.to_s + "   " + "1" + "\n")
      else
        printf(f, req.name + "-" + req.id.to_s + "   " + "0" + "\n")
      end
    }
    printf(f, "/" + "\n\n")


    # Geschlechter   --------------------

    # Weiblich
    printf(f, "Parameter\n  GWV(i) /\n")
    @nannies = Nanny.all
    @nannies.each { |l|
      if l.sex == "w"
        printf(f, l.name + "   " + "1" + "\n")
      else
        printf(f, l.name + "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")

    printf(f, "Parameter\n  GWG(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |l|
      if l.sex == "w"
        printf(f, l.name + "-" + l.id.to_s + "   " + "1" + "\n")
      else
        printf(f, l.name + "-" + l.id.to_s + "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")

    # Männlich
    printf(f, "Parameter\n  GMV(i) /\n")
    @nannies = Nanny.all
    @nannies.each { |l|
      if l.sex == "m"
        printf(f, l.name + "   " + "1" + "\n")
      else
        printf(f, l.name + "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")

    printf(f, "Parameter\n  GMG(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |l|
      if l.sex == "m"
        printf(f, l.name + "-" + l.id.to_s+ "   " + "1" + "\n")
      else
        printf(f, l.name + "-" + l.id.to_s+ "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")

    # Egal
    printf(f, "Parameter\n  bG(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |l|
      if l.sex == "egal" or l.sex == nil
        printf(f, l.name + "-" + l.id.to_s+ "   " + "1" + "\n")
      else
        printf(f, l.name + "-" + l.id.to_s+ "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")


    # Ausbildung

    printf(f, "Parameter\n  aV(i) /\n")
    @nannies = Nanny.all
    @nannies.each { |l|
      if l.education == true
        printf(f, l.name + "   " + "1" + "\n")
      else
        printf(f, l.name + "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")

    printf(f, "Parameter\n  aG(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)
    @requests.each { |l|
      if l.education == true
        printf(f, l.name + "-" + l.id.to_s + "   " + "1" + "\n")
      else
        printf(f, l.name + "-" + l.id.to_s + "   " + "0" + "\n")

      end
    }
    printf(f, "/" + "\n\n")

    # Egal
    printf(f, "Parameter\n  bA(j) /\n")
    @requests = Request.where("status = ? OR status = ?", 0, 2)

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= bootstrap_form_for(@request, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-6") do |f| %>

    <br>
    <h3 align="center"> Datum und Zeitraum </h3>

    <br>

    <% if admin? == false %>
        <%= f.hidden_field :name, label: "Name", value: current_user.name %>

    <% else %>
        <%= f.collection_select :name, User.where(role: "client"), :name, :name, label_class: "labeltext", label: "Nutzername" %>
    <% end %>

    <%= f.hidden_field :status, label: "Status", value: 0 %>

    <%

      # Hier wird ein Array mit den möglichen Daten erstellt

      $i = 0
      $num = 7
      datearray = Array.new

      while $i < $num do

        date = Date.today + $i

        datearray.push(date)

        $i +=1

      end
    %>

    <%= f.select :date, datearray, {label: "Datum*", label_class: "labeltext"}, {class: "selectpicker"} %>
    <%= f.form_group :time, label: {text: "Zeit*", class: "labeltext", required: true} do %>
        <%= f.radio_button :time, "morning", label: "Morgens", label_class: "labeltext-light", inline: true %>
        <%= f.radio_button :time, "noon", label: "Mittags", label_class: "labeltext-light", inline: true %>
        <%= f.radio_button :time, "afternoon", label: "Nachmittags", label_class: "labeltext-light", inline: true %>
        <%= f.radio_button :time, "evening", label: "Abends", label_class: "labeltext-light", inline: true %>

    <% end %>
    <br>
    <br>
    <h3> Anforderungen an die Nanny </h3>
    <br>
    <%= f.number_field :willingness_to_pay, label: "Maximaler Preis", label_class: "labeltext" %>
    <%= f.number_field :minage, label: "Mindestalter", label_class: "labeltext" %>
    <%= f.number_field :maxage, label: "Maximalalter", label_class: "labeltext" %>
    <%= f.form_group :sex, label: {text: "Geschlecht:", class: "labeltext"} do %>
        <%= f.radio_button :sex, "m", label: "Männlich", inline: true, label_class: "labeltext-light" %>
        <%= f.radio_button :sex, "w", label: "Weiblich", inline: true, label_class: "labeltext-light" %>
        <%= f.radio_button :sex, "egal", label: "Egal", inline: true, label_class: "labeltext-light" %>
    <% end %>
    <br>

    <%= f.select :rating, [["egal", 0], [1], [2], [3], [4], [5]], {label: "Mindestbewertung", label_class: "labeltext"}, {class: "selectpicker"} %>


    <%= f.form_group do %>

        <h5> Sprachkenntnisse: </h5>

        <%= f.check_box :language_german, icon: "road", label: "Deutsch", label_class: "labeltext-light" %>
        <%= f.check_box :language_spanish, icon: "road", label: "Spanisch", label_class: "labeltext-light" %>
        <%= f.check_box :language_polish, icon: "road", label: "Polnisch", label_class: "labeltext-light" %>
        <%= f.check_box :language_english, icon: "road", label: "Englisch", label_class: "labeltext-light" %>
        <br>

        <h5> Sonstiges: </h5>
        <%= f.check_box :education, label: "Ausbildung", label_class: "labeltext-light" %>
        <%= f.check_box :driverlicense, label: "Führerschein", label_class: "labeltext-light" %>
        <br>

    <% end %>

    <br>

    <%= f.form_group do %>
        <h4 align="center"> <%= f.submit "Abschicken", class: "homebutton hvr-back-pulse-own" %></h4>
        <h4>Pflichtfelder sind mit einem * markiert.</h4>

    <% end %>

<% end %>

app/views/requests/index.html.erb
<% provide(:title, 'Aufträge') %>

<script>
  $('.datatable').DataTable({});
</script>

<h1>Aufträge</h1>

<div align="center">
  <%= link_to "Datatables-View öffnen", requestsdatatable_path, class: 'reqcard-grey hvr-back-pulse-own' %>
  <br>
  <br>
  <%= link_to "Nur vergangene Aufträge", {:controller => "requests", :action => "index", :whichview => "onlyold"}, class: 'reqcard-grey hvr-back-pulse-own' %>
  <%= link_to "Letzte Woche", {:controller => "requests", :action => "index", :whichview => "lastweek"}, class: 'reqcard-grey hvr-back-pulse-own' %>

  <%= link_to "Nur neue Aufträge ", {:controller => "requests", :action => "index", :whichview => "onlynew"}, class: 'reqcard-grey hvr-back-pulse-own' %>
  <%= link_to "Alle Aufträge", {:controller => "requests", :action => "index", :whichview => "all"}, class: 'reqcard-grey hvr-back-pulse-own' %>
</div>
<!-- Tabelle -->

<br>

<!-- Überschriften -->
<div align="center">
  <div class="avacard-head">Kunden-Name</div>
  <div class="avacard-head">Datum</div>
  <div class="avacard-head-medium">Zeit</div>

  <% if client? or admin? %>
      <div class="avacard-head">Zugeordnete Nanny</div>
      <div class="avacard-head-small">Status</div>
      <div class="avacard-head-medium"></div>
      <div class="avacard-head-medium"></div>
      <div class="avacard-head-medium"></div>

  <% else %>
      <div class="avacard-head-medium"></div>

  <% end %>

  <br>

  <% @requests.each do |request| %>

      <div id="requestname" class="avacard"><%= request.name %></div>
      <div id="weekday" class="avacard">

        <%= week_day = request.date.to_date.wday # Returns the day of week (0-6, Sunday is zero)
            I18n.t('date.day_names')[week_day]
        %>
        <%
          # Datum "übersetzen"
          date = request.date
          datesplitted = date.split("-")
          year = datesplitted[0]
          month = datesplitted[1]
          day = datesplitted[2]

          thedate = day + "." + month + "." + year

          # Zeit übersetzen

          time = request.time

          if time == "morning"
            germantime = "Morgens"
          elsif time == "noon"
            germantime = "Mittags"
          elsif time == "afternoon"
            germantime = "Nachmittags"
          elsif time == "evening"
            germantime = "Abends"
          end
        %>
        <%= thedate %>
      </div>

      <div id="time" class="avacard-medium"><%= germantime %></div>

      <% # Anzeige wenn role = client %>

      <% if client? or admin? %>
          <div id="assignednanny" class="avacard"><%= request.assigned_nanny %></div>

          <% if request.status == 1 %>
              <div class="avacard-true">Zugeordnet</div>
          <% elsif request.status == 2 %>
              <div class="avacard-yellow">Ausstehend</div>
          <% elsif request.status == 3 %>
              <div class="avacard-false">Vergangen</div>
          <% else %>
              <div class="avacard-yellow">Neu</div>

          <% end %>

          <%= link_to 'Anzeigen', request, class: 'avacard-medium hvr-back-pulse-own' %>

          <% if request.assigned_nanny == nil %>
              <%= link_to 'Bearbeiten', edit_request_path(request), class: 'avacard-medium hvr-back-pulse-own' %>
              <%= link_to 'Löschen', request, method: :delete, class: 'avacard-medium hvr-back-pulse-own', data: {confirm: 'Willst du den Auftrag wirklich löschen?'} %>
          <%

            else
              # Wenn das Datum in der Vergangenheit liegt, erscheint ein Button zum Bewerten der Nanny.
              if client? or admin? and request.date.to_date.past? == true and request.ratingdone != true and request.status==1 %>
                  <%= link_to 'Nanny bewerten', request, class: 'avacard-medium hvr-back-pulse-own' %>
                  <div class="avacard-medium"></div>

              <% else %>

                  <div class="avacard-medium"></div>
                  <div class="avacard-medium"></div>
              <% end %>
          <% end %>
      <% else %>
          <%= link_to 'Anzeigen', request, class: 'avacard-medium' %>

      <% end %>
      <br>
  <% end %>
  <br>

</div>

app/views/requests/new.html.erb
<% provide(:title, 'Neue Anfrage') %>

<h1>Neue Anfrage</h1>

<%= render 'form' %>

app/views/requests/show.html.erb
<% provide(:title, @request.name) %>

<% # Den das Modell des entsprechenden Kunden finden:

   @theclient = User.find_by_name(@request.name)

   # Die Request-Time "übersetzen"

   time = @request.time

   if time == "morning"
     germantime = "Morgens"
   elsif time == "noon"
     germantime = "Mittags"
   elsif time == "afternoon"
     germantime = "Nachmittags"
   elsif time == "evening"
     germantime = "Abends"
   end

   # Das Datum "übersetzen"

   date = @request.date
   datesplitted = date.split("-")
   year = datesplitted[0]
   month = datesplitted[1]
   day = datesplitted[2]

   thedate = day + "." + month + "." + year

%>

<div align="center" class="centeredtable">

  <h1>Daten zum Auftrag</h1>

  <h3><%= thedate %> <%= germantime %></h3>

  <br>

  <!-- Bewertung für diese Nanny angeben -->

  <% if client? or admin? and @request.date.to_date.past? == true and @request.ratingdone != true and @request.status==1 %>

      <h2>Wie zufrieden warst du mit deiner Nanny?</h2>

      <h4>(5 = sehr gut, 1 = sehr schlecht)</h4>


      <%= link_to "1", {:controller => "nannies", :action => "rate_nanny", :newrating => 1, :nannyname => @request.assigned_nanny, :requestid => @request.id}, class: "rateingcard" %>

      <br>
      <%= link_to "2", {:controller => "nannies", :action => "rate_nanny", :newrating => 2, :nannyname => @request.assigned_nanny, :requestid => @request.id}, class: "rateingcard" %>

      <br>

      <%= link_to "3", {:controller => "nannies", :action => "rate_nanny", :newrating => 3, :nannyname => @request.assigned_nanny, :requestid => @request.id}, class: "rateingcard" %>
      <br>

      <%= link_to "4", {:controller => "nannies", :action => "rate_nanny", :newrating => 4, :nannyname => @request.assigned_nanny, :requestid => @request.id}, class: "rateingcard" %>
      <br>

      <%= link_to "5", {:controller => "nannies", :action => "rate_nanny", :newrating => 5, :nannyname => @request.assigned_nanny, :requestid => @request.id}, class: "rateingcard" %>

      <br>
      <br>
      <br>

  <% end %>

  <% if @request.date.to_date.past? == true and @request.ratingdone == true %>

      <h2>Die Nanny wurde bei diesem Auftrag mit <%= @request.ratingvalue %> bewertet.</h2>
      <br>

  <% end %>

  <h3>Daten des Kunden</h3>

  <div class="profilcard">Name</div>
  <div class="profilcard"><%= @request.name %></div>
  <br>
  <div class="profilcard">Stadt</div>
  <div class="profilcard"><%= @theclient.city %></div>
  <br>
  <div class="profilcard">Straße</div>
  <div class="profilcard"><%= @theclient.street %></div>
  <br>
  <br>

  <% @currentnanny = Nanny.find_by_name(@request.assigned_nanny) %>

  <h3>Zugeordnete Nanny</h3>
  <% if @request.assigned_nanny == nil %>

      <div class="profilcard-nonanny">Noch keine Nanny zugewiesen!</div>

  <% else %>


      <%

        if @currentnanny == nil %>

          <div class="profilcard"><%= @request.assigned_nanny %></div>

          <h4>Der Nanny-Account existiert nicht mehr. <br> (Daher können die Nanny-Daten nicht eingesehen werden)</h4>

      <% else %>

          <%= link_to @request.assigned_nanny, @currentnanny, class: "profilcard" %>

          <br>

          <!-- Sterne Bewertung Anzeigen -->

          <% numberofstars = @currentnanny.rating.to_i

             (1..numberofstars).each do |n| %>

              <span class="glyphicon glyphicon-star"></span>

          <% end

             numberofemptystars = 5 - numberofstars
             (1..numberofemptystars).each do |n| %>

              <span class="glyphicon glyphicon-star-empty"></span>

          <% end
             end

             end %>
  <br>

  <br>

  <h3>Gewünschte Nanny Daten</h3>

  <!-- Sterne Bewertung Anzeigen -->


  <% @currentnanny = @request %>

  <%
    numberofstars = @currentnanny.rating.to_i

    (1..numberofstars).each do |n| %>

      <span class="glyphicon glyphicon-star"></span>

  <% end

     numberofemptystars = 5 - numberofstars
     (1..numberofemptystars).each do |n| %>

      <span class="glyphicon glyphicon-star-empty"></span>

  <% end %>

  <br>
  <br>


  <div class="profilcard">Maximaler Preis</div>
  <div class="profilcard"><%= @currentnanny.willingness_to_pay.to_s + "0 €" %></div>
  <br>
  <div class="profilcard">Geschlecht</div>
  <div class="profilcard">
    <% if @currentnanny.sex == "w" %> Weiblich
    <% else
         if @currentnanny.sex == "m" %> Männlich
        <% else
             @currentnanny.sex == "egal" %> Keine Angaben
        <% end end %></div>
  <br>
  <div class="profilcard">Minimales Alter</div>
  <div class="profilcard"><%= @currentnanny.minage %></div>
  <br>
  <div class="profilcard">Maximales Alter</div>
  <div class="profilcard"><%= @currentnanny.maxage %></div>
  <br>
  <div class="profilcard">Ausbildung</div>
  <div class="profilcard">
    <% if @currentnanny.education == true %> Ja
    <% else %> Nein
    <% end %></div>
  <br>
  <div class="profilcard">Führerschein</div>
  <div class="profilcard">
    <% if @currentnanny.driverlicense == true %> Ja
    <% else %> Nein
    <% end %></div>
  <br>
  <div class="profilcard">Deutsch-Kenntnisse</div>
  <div class="profilcard">
    <% if @currentnanny.language_german == true %> Ja
    <% else %> Nein
    <% end %></div>
  <br>
  <div class="profilcard">Englisch-Kenntnisse</div>
  <div class="profilcard">
    <% if @currentnanny.language_english == true %> Ja
    <% else %> Nein
    <% end %></div>
  <br>
  <div class="profilcard">Spanisch-Kenntnisse</div>
  <div class="profilcard">
    <% if @currentnanny.language_spanish == true %> Ja
    <% else %> Nein
    <% end %></div>
  <br>
  <div class="profilcard">Polnisch-Kenntnisse</div>
  <div class="profilcard">
    <% if @currentnanny.language_polish == true %> Ja
    <% else %> Nein
    <% end %></div>
  <br>
  <br>
  <br>
  <%= link_to "Jetzt bezahlen", @request, class: "homebutton hvr-buzz-out hvr-fade" %>
  <br>
  <br>
  <br>
  <% if !nanny? %>
      <%= link_to "Auftrag bearbeiten", edit_request_path, class: "reqcard-grey hvr-fade" %>
      <br>
  <% end %>
  <%= link_to "Zurück", requests_path, class: "reqcard-grey hvr-fade" %>

  <br>


</div>