config/routes.rb
Rails.application.routes.draw do
  resources :options
  resources :requests
  resources :availabilities
  resources :nannies
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  post   'help'   => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'admin_controll'    => 'static_pages#admin_controll'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  # Links für Header
  get 'nannies'    => 'nannies#index'
  get 'admin_optimize'  => 'static_pages#admin_optimize'
  get 'requests'    => 'requests#index'
  get 'availabilities'    => 'availabilities#index'
  get 'newnanny' => 'users#newnanny'
  get 'allclients' => 'users#indexclient'
  get 'nanniesedit'    => 'nannies#edit'
  get 'optimize'    => 'requests#optimize'
  get 'simulator'   => 'static_pages#simulator'


  # Sonstige
  get 'noaccess'    => 'static_pages#noaccess'
  get 'requestsdatatable'  => 'requests#requestsdatatable'
  get 'addtimes'    => 'availabilities#addtimes'
  get 'gamstest'    => 'options#gamstest'
  get 'read_solution'    => 'application#read_solution'
  get 'rate_nanny'    => 'nannies#rate_nanny'


  # Links für Simulator
  get 'randomrequest'   => 'simulators#randomrequest'
  get 'randompast'   => 'simulators#randompast'
  get 'tenrandompasts'   => 'simulators#tenrandompasts'
  get 'tenrandomrequests'   => 'simulators#tenrandomrequests'
  get 'randomclient'   => 'simulators#randomclient'
  get 'randomnanny'   => 'simulators#randomnanny'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

    EmergencyNanny (C) 2017  |  by PacziGebski

  </small>
  <nav>
    <ul>
      <li><%= link_to "Informationen",   about_path %></li>
      <li><%= link_to "Hilfe",   help_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">


  <div class="container">
    <%= link_to "EMERGENCY NANNY", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? == false %>
            <li class="hvr-underline-reveal"><%= link_to "Home", root_path %></li>
        <% end %>

        <% if admin? %>
            <li class="hvr-underline-reveal"><%= link_to "Dashboard", admin_controll_path %></li>
            <li class="hvr-underline-reveal"><%= link_to "Simulator", simulator_path %></li>
            <li class="hvr-underline-reveal">
              <%= link_to text_with_badge('Optimieren', Request.where("status = ? OR status = ?", 0, 2).count), admin_optimize_path %>
            </li>
            <li class="hvr-underline-reveal"><%= link_to "Nannys", nannies_path %></li>
            <li class="hvr-underline-reveal"><%= link_to "Aufträge", requests_path %></li>
            <li class="hvr-underline-reveal"><%= link_to "Neue Anfrage", new_request_path %></li>

        <% end %>

        <% if client? %>
            <li class="hvr-underline-reveal"><%= link_to "Meine Anfragen", requests_path %></li>
            <li class="hvr-underline-reveal"><%= link_to "Neue Anfrage", new_request_path %></li>
        <% end %>


        <% if nanny? %>
            <li class="hvr-underline-reveal"><%= link_to "Verfügbarkeiten", availabilities_path %></li>
            <li class="hvr-underline-reveal"><%= link_to "Meine Aufträge", requests_path %></li>
        <% end %>

        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="text-align: left;">

                <%= gravatar_for_header current_user %>
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Mein Profil", current_user %></li>
                <% if admin? %>
                    <li><%= link_to "Alle Nutzer", users_path %></li>
                    <li><%= link_to "Alle Kunden", allclients_path %></li>

                <% end %>

                <% if nanny? %>
                    <li><%= link_to "Nanny-Daten", new_nanny_path %></li>
                <% end %>


                <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li class="hvr-underline-reveal"><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>